import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {getActiveSession, isSessionValid, Session} from "@/lib/auth";
import {cookies} from "next/headers";
import Image from "next/image";
import LinkButton from "@/lib/components/LinkButton";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen h-full`}>
      <div className="flex flex-col items-center justify-baseline min-h-screen h-screen p-8 pb-20 gap-16 bg-linear-to-b from-blue-50 to-cyan-50 dark:from-blue-950 dark:to-cyan-950  sm:p-20 font-[family-name:var(--font-geist-sans)]">
        {children}
      </div>
      </body>
    </html>
  );
}